server.port: 9081

spring:
  application:
    name: kafka-research-consumer

kafka:
  bootstrap-servers: localhost:29092
  schema-registry-url: http://localhost:8081
  reviews:
    id: kafka-research-consumer-1
    topic: REVIEWS_RESEARCHERS_INSTITUTES_ARTICLES
    group-id: kafka-research-consumer-group
    start-offset: earliest
    concurrency: 4
    max-poll-records: 100

elasticsearch:
  host: localhost
  port: 9300
  cluster-name: docker-es-cluster

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
