spring:
  application:
    name: kafka-research-consumer
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema-registry-url: http://localhost:8081
    consumer:
      client-id: kafka-research-consumer-1
      group-id: kafka-research-consumer-group
      topic: REVIEWS_RESEARCHERS_INSTITUTES_ARTICLES
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
    listener:
      ack-mode: MANUAL
      concurrency: 5
  data:
    elasticsearch:
      cluster-name: docker-es-cluster
      cluster-nodes: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9300}
  elasticsearch:
    rest:
      uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
