server.port: 9080

spring:
  application:
    name: research-service
#  jpa:
#    hibernate.ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/researchdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: simulation
  main:
    web-application-type: none
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging.level:
  org.hibernate:
    SQL: INFO
    type.descriptor.sql.BasicBinder: INFO

simulation:
  reviews:
    total: 10
    sleep: 100
