spring:
  application:
    name: research-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/researchdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret

logging.level:
  org.hibernate:
    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC

load-samples:
  articles.enabled: true
  institutes.enabled: true
  researchers.enabled: true

simulation:
  reviews:
    total: 10
    sleep: 100
